# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Chartering New Realms; AI as a Catalyst in Digital Humanities
author: Phillip B. Ströbel
logo: chartering-new-realms-logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: false
  execution_cache_path: _build/.jupyter_cache
  
latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references_chap2.bib

repository:
<<<<<<< HEAD
  url: https://github.com/pstroe/chartering-new-realms-2024
  branch: chapter_2
=======
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  branch: main
>>>>>>> 0d10137568ab72862dfadd0fcd140a5c6cf0891c

html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  config:
    bibtex_reference_style: author_year

launch_buttons:
  thebe: true
  binder_url: https://mybinder.org

# Thebe configuration
thebe:
  binderOptions:
    repo: "pstroe/chartering-new-realms-2024"
  use_jupyterlite: true
  lite_url: "_static/lite"